apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  APP_ENV: "production"
  MONGO_DATABASE: "air-quality"
  MONGODB_CONNECTION: "mongodb"
  MONGODB_HOSTNAME: "mongo:27017"
  PYTHONPATH: "/app/src"
  REPO_NAME: "air-quality-data-dump"
  TZ: "Europe/Skopje"
  VOLUME_PATH: "/var/api"